### ISSUE TITLE
Memory leak error

### ISSUE THREAD

**Issue by silphf** [benelot/pybullet-gym#22]
Hello!
I had found same bug cause by newest numpy version 1.16.0, 
which makes the environments get memory leak.
when I install pybullet-gym with numpy 1.16.0,
the memory use rate become higher and higher...
then I downgrade numpy to 1.15.4, the problem is solved.

**Comment by benelot** [comment]
Can you make a minimal case to reproduce you issue? 

I am pretty sure the problem is not due to my code, but could be related to the pybullet code running below of it. However, a change in numpy version sounds odd to me that it is really a problem related to either pybullet or pybullet-gym.

**Comment by benelot** [comment]
I will close this as it is an older issue. Please feel free to reopen it.
