### ISSUE TITLE
env not rendering

### ISSUE THREAD

**Issue by kartikpaigwar** [benelot/pybullet-gym#25]
import gym
import pybulletgym
import time
env = gym.make('HumanoidPyBulletEnv-v0')
for i_episode in range(500):
    observation = env.reset()
    for t in range(1000):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print(observation)
        time.sleep(1/30)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

**Comment by kartikpaigwar** [comment]
no display while rendering. Please help.

**Comment by LinghengMeng** [comment]
Hi @kartikpaigwar 
Can you try:
`import pybulletgym
import gym
env_name = 'HumanoidPyBulletEnv-v0'
env = gym.make(env_name)

**env.render()**
**env.reset()**

for i in range(10000):
    obs, rewards, done, _ = env.step(env.action_space.sample())`
Please make sure to put `env.render()` before `env.reset()`. I guess it's the way of using render different from openai.gym confuses you.

**Comment by benelot** [comment]
Thanks for helping each other! Did this solve your problem? If anything is
unclear, we could add something to the readme or other docs. Any ideas?

**Comment by kartikpaigwar** [comment]
Yeas it worked, I figured it out. Thanks for the help.

**Comment by benelot** [comment]
Sounds like everything worked. We added a line of help to the readme. Closing this.
