### ISSUE TITLE
How are the environments related with those in bullet3?

### ISSUE THREAD

**Issue by diegoferigo** [benelot/pybullet-gym#33]
@benelot In the upstream bullet3 repository I found https://github.com/bulletphysics/bullet3/pull/1296 and https://github.com/bulletphysics/bullet3/pull/1512. If I understood well, some of the work stored in this repo has been merged upstream. How does pybullet-gym differ from the upstream environments? Which ones should be preferred? Is there any plan about maintenance and improvements?

**Comment by benelot** [comment]
Hi! So there are some that are merged upstream as you correctly found out. In my case I am working on making them more compatible with the ones of the original OpenAI gym, but work progresses slowly towards that. As such, for now they can be considered nearly identical. There are some new envs coming up that are not upstream though. I plan to do maintenance of these envs here and people supporting me with this are highly welcome!

**Comment by diegoferigo** [comment]
Hi @benelot, thanks for shedding some light upon it, got it. I'll keep having a look to the development.
