### ISSUE TITLE
Problem in rendering

### ISSUE THREAD

**Issue by devloper13** [benelot/pybullet-gym#39]
I'm using ReacherPyBulletEnv-v0 and I'm unable to render it.

**Comment by benelot** [comment]
Hi!

Sorry for coming back to you so late. Yes, it is not yet ready to use,
there is a rendering issue. It has to do with the rendere of pybullet and
as such bullet itself. Could you please post the issue to the
https://github.com/bulletphysics/bullet3/issues page and ask mention me
there? It would be great if they realize that people are using the gyms and
are unable to use some stuff. Thanks

**Comment by devloper13** [comment]
I could render it by calling env.render('human') before using env.reset().
