### ISSUE TITLE
How to Cite PyBullet-Gym

### ISSUE THREAD

**Issue by Wook133** [benelot/pybullet-gym#57]
Would you kindly provide a preferred means of citing this library as a bibtex?

Something similar to how PyBullet does it would be appreciated:
@MISC{coumans2019,
author =   {Erwin Coumans and Yunfei Bai},
title =    {PyBullet, a Python module for physics simulation for games, robotics and machine learning},
howpublished = {\url{http://pybullet.org}},
year = {2016--2019}
}

**Comment by Wook133** [comment]
This is how I currently cite your work:
@misc{benelot2018,
author =   {Benjamin Ellenberger},
title =    {PyBullet Gymperium},
howpublished = {\url{https://github.com/benelot/pybullet-gym}},
year = {2018--2019}
}

**Comment by benelot** [comment]
Perfect! I would suggest to cite it exactly the way you suggested it. Where are you citing my work? I am interested.
