### ISSUE TITLE
Trainer modules

### ISSUE THREAD

**Issue by Olimoyo** [benelot/pybullet-gym#9]
I am trying to run the "train_KerasDDPG_ReacherBulletEnv.py" example but it seems that the modules are not being imported properly for me among other issues.

For example, "from ..Trainer import Trainer"  seems to be missing and to be one directory higher. When I do fix this issue, i'm running into other problems such as the method "Trainer.Trainer()" not existing.

I was wondering if I was missing something obvious or if these examples are not up to date anymore?

Thanks!

**Comment by benelot** [comment]
The example is not up to date anymore, but I will fix this soon. For now
you can go some commits back before I moved the files into the roboschool
folder. I am about to restructure the repo and add an implementation of the
mujoco envs of openai gym to the repo. Stay tuned!
